### ISSUE TITLE
Метод в классе GamesStore getSumPlayedTime() всегда возвращает 0.

### ISSUE THREAD

**Issue by zlobryak** [rubbannov/JavaQA-TeamWork#1]
## Описание
Необходимо реализовать метод getSumPlayedTime() так, чтобы он возвращал общее время проведенное за играми для всех игроков этого каталога.
Сейчас он всегда возвращает 0.
## Локация дефекта
https://github.com/rubbannov/JavaQA-TeamWork/blob/bd9578a77a6d29adbe17d23bb9d282e799884ece/src/main/java/ru/netology/GameStore.java#L75-L77
## Шаги воспроизведения
1. Открыть [код](https://github.com/zlobryak/javaqa-team-project.git)
2. Запустить тест    `public void getSumPlayedTime()` в классе   `src/test/java/ru/netology/GameStoreTest.java`
3. Посмотреть на вывод консоли.
## Скриншот
![JavaQA-TeamWork – GameStoreTest java 2023-03-27 22](https://user-images.githubusercontent.com/39959717/228046011-a452e182-0f84-404b-810a-2b9e0d986ee6.png)
## Окружение
- IntelliJ IDEA 2022.3.2 (Community Edition)
- Java OpenJDK 11
- Manjaro 6.1.1.19-1-1
- KDE Plasma 5.26.5
- KDE Frameworks 5.103.0
- Qt 5.15.8

**Comment by rubbannov** [comment]
Функцию реализовал, тест проходит
