### ISSUE TITLE
Не выводится RunTimeException при вводе отрицательных значений в методе play в классе player

### ISSUE THREAD

**Issue by rubbannov** [rubbannov/JavaQA-TeamWork#12]
## Описание
Необходимо добавить исключение к методу `play`, чтобы при вводе отрицательных значений наигранных часов появлялась ошибка с сообщением
## Локация дефекта
https://github.com/rubbannov/JavaQA-TeamWork/blob/e47cce694f11a05fba13c3c823a525af24e63ccf/src/main/java/ru/netology/Player.java#L53-L64
## Шаги воспроизведения
1. Открыть проект **JavaQA-TeamWork** в IDEA
2. Открыть класс `PlayerTest`.
3. Запустить тест `testNegativeHoursPlayGame()`

_Ожидаемый результат_: RunTimeExcteption сообщение о вводе некорректных данных
_Фактический результат_: Expected to be thrown, but nothing was thrown
## Скриншот
![TeamProject – PlayerTest java 2023-04-01 21 43 33](https://user-images.githubusercontent.com/117990332/229308797-d7768cec-2a0e-419d-bc7e-87eb7e0db21d.png)

## Окружение
- IntelliJ IDEA 2022.3.2 (Community Edition)
- Java OpenJDK 11

**Comment by zlobryak** [comment]
Сделал проверку строго больше 0, 0 время игры тоже не должно добавляться.
