### ISSUE TITLE
Метод addPlayTime(String playerName, int hours) класса  GameStore не должен принимать отрицательные значения hours

### ISSUE THREAD

**Issue by zlobryak** [rubbannov/JavaQA-TeamWork#14]
## Описание
В методе `addPlayTime(String playerName, int hours)` стоит реализовать обработку исключений для случаев, когда переменная hours имеет отрицательные значения или равна нулю.

## Локация дефекта
https://github.com/rubbannov/JavaQA-TeamWork/blob/db84ba37d87dfab5d3a0085dc65afc2ab51b4dd4/src/main/java/ru/netology/GameStore.java#L55
## Шаги воспроизведения
1. Открыть [код](src/test/java/ru/netology/GameStoreTest.java)
2. Запустить `void addPlayTimeBelowZero()`
3. Просомтреть результаты в консоли
_Ожидаемый рульузлтат_: Тест проходит.
_Фактичсеский рузультат:_ org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.
## Скриншот
![JavaQA-TeamWork – GameStoreTest java 2023-04-02 18 34 42](https://user-images.githubusercontent.com/39959717/229363180-b130c780-333e-4644-80c4-1add33bf5da5.png)

## Окружение
- IntelliJ IDEA 2022.3.2 (Community Edition)
- Java OpenJDK 11
- Manjaro 6.1.1.19-1-1
- KDE Plasma 5.26.5
- KDE Frameworks 5.103.0
- Qt 5.15.8

**Comment by rubbannov** [comment]
Метод реализован, тесты проходит
