### ISSUE TITLE
Дефект в методе containsGame класса GameStore

### ISSUE THREAD

**Issue by zlobryak** [rubbannov/JavaQA-TeamWork#2]
## Описание
Неправильное значение для переменной в цикле fori.

## Локация дефекта
https://github.com/rubbannov/JavaQA-TeamWork/blob/fd3c9c261059e5dffe284388bbe8faad3b99ef95/src/main/java/ru/netology/GameStore.java#L32-L39

## Шаги воспроизведения

1. Открыть [код](https://github.com/rubbannov/JavaQA-TeamWork/blob/fd3c9c261059e5dffe284388bbe8faad3b99ef95/src/main/java/ru/netology/GameStore.java#L32)
2. Запустить тест     `public void shouldAddGame()`
4. Посмтреть на вывод

Ожидаемый результат: containsGame возвращает True
Фактический результат: containsGame возвращает False

## Скриншот
![JavaQA-TeamWork – GameStoreTest java ShouldAddGame 2023-03-27 22](https://user-images.githubusercontent.com/39959717/228048464-01373b9e-d428-4c98-b2c3-4dea86d0b5b9.png)

## Окружение
- IntelliJ IDEA 2022.3.2 (Community Edition)
- Java OpenJDK 11
- Manjaro 6.1.1.19-1-1
- KDE Plasma 5.26.5
- KDE Frameworks 5.103.0
- Qt 5.15.8

**Comment by rubbannov** [comment]
Метод исправлен, тесты проходит
