### ISSUE TITLE
Мне не хватает метода для создания теста

### ISSUE THREAD

**Issue by zlobryak** [rubbannov/JavaQA-TeamWork#3]
Чтобы протестировать `public void addPlayTime(String playerName, int hours)` не зватает метода, который возвращал бы все время, которое было щаписано одному игроку.
https://github.com/rubbannov/JavaQA-TeamWork/blob/fb277ed0192ae71718dee8934446d4713c60a505/src/main/java/ru/netology/GameStore.java#L46-L52

Написал заранее тест, строка с неработающим кодом закоменчена.
https://github.com/rubbannov/JavaQA-TeamWork/blob/fb277ed0192ae71718dee8934446d4713c60a505/src/test/java/ru/netology/GameStoreTest.java#L18-L25

**Comment by zlobryak** [comment]
Сам метод явно содержит ошибку (новое добавляемое время не суммируется, если игрок уже добавлен в список)
https://github.com/rubbannov/JavaQA-TeamWork/blob/fb277ed0192ae71718dee8934446d4713c60a505/src/main/java/ru/netology/GameStore.java#L48

Нужно ли нам обвешивать такие методы еще и проверками на допустимые принимаемые значения? 
Например - если ввести отрицательное количество времени и тому подобное?

**Comment by rubbannov** [comment]
Метод добавлен, тест проходит
