### ISSUE TITLE
Добавить обработку исключений для метода publishGame(String title, String genre) в классе GameStore

### ISSUE THREAD

**Issue by zlobryak** [rubbannov/JavaQA-TeamWork#4]
## Описание
Добавил тест public void shouldAddGameAlreadyExistException(), который должен проверять возвращение исключения при попытке записать уже уже существующей игры.
Необходимо добавить класс `AlreadyExistException.class` и добавить в метод `publishGame(String title, String genre)` обработку исключения.

## Локация дефекта
https://github.com/rubbannov/JavaQA-TeamWork/blob/b4ec367f2af415e58e792e614468f63e19102947/src/main/java/ru/netology/GameStore.java#L22-L26

**Comment by rubbannov** [comment]
Обработка исключений для метода publishGame добавлена, тест пройден
