### ISSUE TITLE
Отсутствует функция вывода списка уже установленных игр в классе Player

### ISSUE THREAD

**Issue by rubbannov** [rubbannov/JavaQA-TeamWork#5]
## Описание
Для проверки функции `installGame` требуется функция возвращающая список установленных игр
## Локация дефекта
https://github.com/rubbannov/JavaQA-TeamWork/blob/6dee8e8adcdf27c0c3e6dd47a60ec39eb5b04f41/src/test/java/ru/netology/PlayerTest.java#L29-L33

**Comment by zlobryak** [comment]
Я сходу не разобрался как потом перегнать список в массив, но это лишний шаг уже, стандартными методами можно сразу вернуть список всех игр.

Написал сам себе тест для проверки, не стал уже удалять.

**Comment by rubbannov** [comment]
Написано правильно, тест проходит, но я ожидал увидеть в тестах такой вариант ожидаемого результата `expected = {game1, game2, game3, game4, game5};`
Чтобы яснее видеть как образуется список установленных игр.

**Comment by zlobryak** [comment]
Сам класс хранит объекты игр в HashMap, который хранит значения в произвольном порядке. Если выводить список и потом перегонять его в массив - они будут не в том порядке, в котором их добавляли.
