### ISSUE TITLE
Отсутствует функция проверки наличия/отсутствия игры

### ISSUE THREAD

**Issue by rubbannov** [rubbannov/JavaQA-TeamWork#6]
## Описание
Необходимо дописать функцию `installGame` чтобы при её вызове она проверяла наличие этой игры у игрока. В случае наличия игры - ничего происходить не должно. А именно счетчик часов не должен обнулиться.
## Локация дефекта
https://github.com/rubbannov/JavaQA-TeamWork/blob/6dee8e8adcdf27c0c3e6dd47a60ec39eb5b04f41/src/main/java/ru/netology/Player.java#L25-L29

**Comment by zlobryak** [comment]
Добавил класс `AlreadyExistException` и проверку в метод, теперь он возвращает ошибку, если попытаться добавить уже существующую игру.
Это было в этом коммите a08cbdf146d6854e5721500b82409cff8e83db14

**Comment by rubbannov** [comment]
Согласен. Тест проходит, можно закрыть данный issue
